### ISSUE TITLE
Front and Backend:  Confirm data schema for books and categories

### ISSUE THREAD

**Issue by tas09009** [FreeOpenUniversity/website-backend#51]

**Comment by tas09009** [comment]
![OpenU_Database_schema_updated](https://user-images.githubusercontent.com/8211605/104945602-fb355c00-5986-11eb-91e0-dd76e4c0e7c2.png)

This is the updated schema for what we have. May need to change this

**Comment by linesbetween** [comment]
Looks good! 
In the future, we may separate book image and category image into different tables.

**Comment by tas09009** [comment]
Yeah that makes sense
